language: scala
scala:
  - 2.11.8
  - 2.12.1
jdk:
  - oraclejdk8
sudo: false
script:
  - sbt test transferPublishAndTagResources
  - scripts/publishAndTag 'slamdata/scala-abt'
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
